
# External dependencies

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "4.0"
RULES_JVM_EXTERNAL_SHA = "31701ad93dbfe544d597dbe62c9a1fdd76d81d8a9150c2bf1ecf928ecdf97169"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "io.vertx:vertx-stack-depchain:4.0.3",
        "io.vertx:vertx-web:4.0.3",
        "io.vertx:vertx-web-client:4.0.3",
        "io.vertx:vertx-rx-java2:4.0.3",
        "io.vertx:vertx-junit5:4.0.3",
        "org.junit.jupiter:junit-jupiter:5.7.0",
    ],
    repositories = [
        "https://maven-central-eu.storage-download.googleapis.com/maven2",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
        "https://packages.confluent.io/maven/",
        "https://jcenter.bintray.com/",
    ],
)